[build]
  command = "npm run build"
  publish  = "dist"

[build.environment]
  VITE_SUPABASE_URL = "https://qiyywaouaqpvojqeqxnv.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."

[functions]
  directory    = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]

  from = "/send-order-received"
  to = "/.netlify/functions/send-order-received"
  status = 200

  from = "/*"
  to   = "/index.html"
  status = 200
