[build]
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_SUPABASE_URL = "https://qiyywaouaqpvojqeqxnv.supabase.co"
  VITE_SUPABASE_ANON_KEY = "<eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpeXl3YW91YXFwdm9qcWVxeG52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NTk4NzcsImV4cCI6MjA2ODIzNTg3N30.EVeuMswYZeK4g8kqwJuH4ANsTyOPAqoFpTH_AD9CCIU>"
[build]
  command = "npm run build"
  publish = "dist"

# แนะนำให้ย้าย ENV ไปตั้งใน Netlify UI (Site settings → Build & deploy → Environment)
# ถ้าจำเป็นต้องเก็บไว้ในไฟล์ ให้คงรูปแบบนี้ไว้
[build.environment]
  VITE_SUPABASE_URL = "https://qiyywaouaqpvojqeqxnv.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpeXl3YW91YXFwdm9qcWVxeG52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NTk4NzcsImV4cCI6MjA2ODIzNTg3N30.EVeuMswYZeK4g8kqwJuH4ANsTyOPAqoFpTH_AD9CCIU"

# (แนะนำ) SPA redirect สำหรับ React Router ให้ทุกเส้นทางวิ่งเข้า index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
