[build]
  command = "npm run build"
  publish  = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_SUPABASE_URL = "https://qiyywaouaqpvojqeqxnv.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."

[functions]
  directory    = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
