[build]
  command = "npm run build"
  publish  = "dist"

[build.environment]
  # (ใช้ได้สำหรับ build-time) — ถ้าจะ pin Node เวอร์ชันให้ขั้น build
  NODE_VERSION = "20"

  VITE_SUPABASE_URL = "https://qiyywaouaqpvojqeqxnv.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpeXl3YW91YXFwdm9qcWVxeG52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NTk4NzcsImV4cCI6MjA2ODIzNTg3N30.EVeuMswYZeK4g8kqwJuH4ANsTyOPAqoFpTH_AD9CCIU"

[functions]
  directory    = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["nodemailer"]
  

# ---- Redirects ต้องแยกเป็น 2 บล็อก ----
[[redirects]]
  from = "/send-order-received"
  to   = "/.netlify/functions/send-order-received"
  status = 200

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
